"use client";
import RequestUpdate from "./RequestUpdate";
import { useState } from "react";
import Link from "next/link";
import { api, money } from "@/services/api";
import { useResource } from "@/hooks/useResource";
import Fields, { Upload, FileLink, type Field, type Value } from "./Fields";
import { State, type Row } from "./Workspace";
type Booking = Row & { creator: string; startTime: string; endTime: string; instructions: string; venue?: string; packageName?: string; commissionAmount: number; commissionRate: number; workflow: string; workflowStage?: string; project?: { _id: string }; contacts?: { creator?: { email?: string; phone?: string }; customer?: { email?: string; phone?: string } }; history: { status?: string; stage?: string; at: string; reason?: string; note?: string }[] };
type Delivery = Row & { version: number; album: string; revisions: { comment: string; timestamp?: string }[] };
export default function BookingDetail({ id, role }: { id: string; role: string }) {
  const r = useResource<Booking>(`/bookings/${id}`), deliveries = useResource<Delivery[]>(`/deliveries?booking=${id}`);
  const [error, setError] = useState(""), [busy, setBusy] = useState(false), [files, setFiles] = useState<string[]>([]), [comment, setComment] = useState("");
  const b = r.data;
  const completion = useResource<{ fields: Field[] }>("/forms?context=SERVICE_COMPLETION&category=" + encodeURIComponent(b?.service || ""));
  const [completionAnswers, setCompletionAnswers] = useState<Record<string, Value>>({});
  async function action(name: string) { setBusy(true); setError(""); try { await api(`/bookings/${id}/actions`, { method: "POST", body: JSON.stringify({ action: name, answers: completionAnswers }) }); await r.reload(); } catch (e) { setError(e instanceof Error ? e.message : "Action failed."); } finally { setBusy(false); } }
  const creator = role === "creator";
  const buttons: [string, string][] = !b ? [] : creator ? b.status === "SENT_TO_CREATOR" ? [["accept", "Accept request"], ["decline", "Decline request"]] : b.status === "CONFIRMED" ? [["start", "Start project"]] : ["IN_PROGRESS", "REVISION_REQUESTED"].includes(b.status || "") && b.workflow !== "DIGITAL" ? [["complete-service", "Mark service delivered"]] : [] : ["AWAITING_CLIENT_CONFIRMATION", "AWAITING_PAYMENT"].includes(b.status || "") ? [["confirm", "Confirm booking details"]] : b.status === "DELIVERED" ? [["complete", "Confirm completion"]] : [];
  return <><State {...r} />{b && <><div className="rounded-xl border bg-white p-6 mb-6"><div className="flex flex-wrap justify-between gap-4"><h2 className="display text-3xl">{b.title}</h2><span className="badge">{b.status?.replaceAll("_", " ")}</span></div><p className="muted">{b.date} · {b.startTime}–{b.endTime} · {b.city}</p><p className="text-2xl font-semibold">{money(b.amount || 0)}</p><p className="muted text-xs">Payment: {b.paymentStatus} · Commission: {b.commissionRate}% ({money(b.commissionAmount || 0)})</p><p className="whitespace-pre-wrap">{b.instructions}</p>{b.venue && <p>Venue: {b.venue}</p>}<p className="muted text-xs">Booking ID: {id}</p>{b.contacts && <div className="rounded-lg bg-purple-50 p-4 text-sm">Contact details unlocked: {creator ? b.contacts.customer?.email : b.contacts.creator?.email} · {creator ? b.contacts.customer?.phone : b.contacts.creator?.phone}</div>}{buttons.some(([name]) => name === "complete-service") && <Fields fields={completion.data?.fields || []} values={completionAnswers} onChange={(id, value) => setCompletionAnswers(a => ({ ...a, [id]: value }))} />}<div className="flex flex-wrap gap-3 mt-5">{buttons.map(([name, label]) => <button className="btn" disabled={busy} onClick={() => action(name)} key={name}>{label}</button>)}{!["PENDING_ADMIN_REVIEW", "ADMIN_REJECTED", "NEEDS_INFORMATION"].includes(b.status || "") && <button className="btn btn-outline" onClick={async () => { try { await api("/conversations", { method: "POST", body: JSON.stringify({ context: "BOOKING", entityId: id }) }); window.location.href = `/${role}/messages`; } catch (e) { setError(e instanceof Error ? e.message : "Cannot open chat."); } }}>Open project chat</button>}{!["COMPLETED", "CANCELLED", "REFUNDED", "REFUND_PENDING"].includes(b.status || "") && <button className="text-sm underline text-red-700" disabled={busy} onClick={() => { if (confirm("Cancel this booking? Paid bookings will enter refund review.")) void action("cancel"); }}>Cancel booking</button>}</div>{error && <p role="alert" className="error-box mt-4">{error}</p>}</div>
    {!creator && ["PENDING_ADMIN_REVIEW", "NEEDS_INFORMATION"].includes(b.status || "") && <RequestUpdate resource="bookings" id={id} value={b.instructions} onSaved={r.reload} />}
    {b.project && <section className="rounded-xl border bg-white p-6 space-y-5"><h2 className="display text-3xl">Project workspace</h2><p className="muted text-sm">Keep plans and files together, review deliveries, and request revisions here.</p>
      {creator && b.workflow === "RENTAL" && ["CONFIRMED", "IN_PROGRESS"].includes(b.status || "") && <form className="space-y-3" onSubmit={async e => { e.preventDefault(); const body = Object.fromEntries(new FormData(e.currentTarget)); try { await api(`/bookings/${id}/workflow`, { method: "PATCH", body: JSON.stringify(body) }); await r.reload(); } catch (e) { setError(e instanceof Error ? e.message : "Cannot update stage."); } }}><label className="field">Rental stage (current: {b.workflowStage || "Confirmed"})<select name="stage">{["PICKUP_PENDING", "PICKED_UP", "IN_RENTAL", "RETURN_PENDING", "RETURNED", "INSPECTION"].map(s => <option key={s}>{s}</option>)}</select></label><label className="field">Condition / handover notes<textarea name="notes" required /></label><button className="btn">Update rental stage</button></form>}
      {creator && !["COMPLETED", "CANCELLED", "DISPUTED"].includes(b.status || "") && <form className="space-y-4 border-b pb-6" onSubmit={async e => { e.preventDefault(); const form = e.currentTarget; setBusy(true); setError(""); try { await api("/deliveries", { method: "POST", body: JSON.stringify({ ...Object.fromEntries(new FormData(form)), booking: id, files }) }); form.reset(); setFiles([]); await Promise.all([r.reload(), deliveries.reload()]); } catch (e) { setError(e instanceof Error ? e.message : "Delivery failed."); } finally { setBusy(false); } }}><label className="field">Delivery title<input name="title" required placeholder="Wedding highlights — version 1" /></label><label className="field">Album / folder<input name="album" placeholder="Ceremony" /></label><label className="field">Description<textarea name="description" required /></label><Upload purpose="delivery" contextId={id} values={files} onChange={setFiles} /><button className="btn" disabled={busy || !files.length}>Send delivery</button></form>}
      <State {...deliveries} />{deliveries.data?.map(d => <article key={d._id} className="rounded-lg border p-4 space-y-3"><h3 className="font-semibold">{d.title} · V{d.version}</h3><span className="badge">{d.status}</span><p className="muted">{d.description}</p><div className="flex flex-wrap gap-3">{d.files?.map((f, i) => <FileLink key={f} id={f} label={`File ${i + 1}`} />)}</div>{d.revisions.map((rev, i) => <p className="text-sm" key={i}>{rev.timestamp} {rev.comment}</p>)}{!creator && d.status !== "APPROVED" && ["DELIVERED", "REVISION_REQUESTED"].includes(b.status || "") && <div className="space-y-3"><textarea className="input" aria-label="Revision notes" placeholder="Describe requested changes; include video timestamps where helpful." value={comment} onChange={e => setComment(e.target.value)} /><div className="flex flex-wrap gap-3">{["approve", "revision"].map(a => <button type="button" className="btn btn-outline" key={a} disabled={busy} onClick={async () => { setBusy(true); setError(""); try { await api(`/deliveries/${d._id}/review`, { method: "POST", body: JSON.stringify({ action: a, comment }) }); await Promise.all([r.reload(), deliveries.reload()]); } catch (e) { setError(e instanceof Error ? e.message : "Review failed."); } finally { setBusy(false); } }}>{a === "approve" ? "Approve delivery" : "Request revision"}</button>)}</div></div>}</article>)}{!deliveries.data?.length && <p className="muted">No deliveries yet.</p>}
      {!creator && b.status === "COMPLETED" && <Review creator={b.creator} />}
      <Link className="text-sm underline" href="/customer/disputes">Report a problem with this booking</Link>
    </section>}<section className="mt-8"><h2 className="display text-2xl">Timeline</h2>{b.history.map((h, i) => <div className="border-l-2 border-purple-200 pl-4 py-3 text-sm" key={i}><b>{h.status || h.stage}</b><p className="muted mb-0">{new Date(h.at).toLocaleString()} {h.reason || h.note}</p></div>)}</section></>}</>;
}
function Review({ creator }: { creator: string }) { const [result, setResult] = useState(""); return <form className="space-y-3" onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); try { await api("/reviews", { method: "POST", body: JSON.stringify({ creator, rating: Number(f.get("rating")), comment: f.get("comment") }) }); setResult("Review submitted for moderation."); } catch (e) { setResult(e instanceof Error ? e.message : "Could not submit review."); } }}><h3 className="font-semibold">Share your experience</h3><label className="field">Rating<select name="rating">{[5, 4, 3, 2, 1].map(n => <option key={n}>{n}</option>)}</select></label><label className="field">Review<textarea name="comment" required minLength={10} /></label><button className="btn">Submit review</button><p role="status">{result}</p></form>; }
