"use client";
import { useState } from "react";
import Link from "next/link";
import { api } from "@/services/api";
import { useResource } from "@/hooks/useResource";
import type { Creator } from "@/services/types";
import { State } from "./Workspace";
import { Upload } from "./Fields";
type Slot = { date: string; startTime: string; endTime: string; blocked: boolean };
type Profile = Creator & { applicationStatus: string; reviewReason?: string; verified: boolean; businessType: string; languages: string[]; experience: number; serviceAreas: string[]; travelAvailable: boolean; eventTypes: string[]; timeSlots: Slot[]; weeklyHours: { weekday: number; startTime: string; endTime: string }[]; temporaryLocations: { city: string; from: string; until: string }[] };
export default function CreatorSettings({ section }: { section: string }) {
  const r = useResource<{ profile: Profile | null; verification?: { _id: string; originalFilename: string; extension: string }[] }>("/creator-workspace");
  return <><State {...r} />{r.data?.profile ? <Editor key={`${section}-${r.data.profile._id}-${r.data.profile.applicationStatus}`} section={section} profile={r.data.profile} verification={r.data.verification || []} reload={r.reload} /> : r.data && <div><p className="muted">Start your creator application to set up your professional workspace.</p><Link href="/join" className="btn">Become a creator</Link></div>}</>;
}
function Editor({ section, profile, verification, reload }: { section: string; profile: Profile; verification: { _id: string; originalFilename: string; extension: string }[]; reload: () => Promise<void> }) {
  const [c, setC] = useState({ ...profile, state: profile.state || "", businessType: profile.businessType || "INDIVIDUAL", languages: profile.languages || [], experience: profile.experience || 0, serviceAreas: profile.serviceAreas || [], eventTypes: profile.eventTypes || [], timeSlots: profile.timeSlots || [], weeklyHours: profile.weeklyHours || [], temporaryLocations: profile.temporaryLocations || [] });
  const [error, setError] = useState(""), [success, setSuccess] = useState(""), [busy, setBusy] = useState(false), [assets, setAssets] = useState(verification.map(v => v._id));
  const calendar = section === "calendar";
  if (section === "verification") return <div className="rounded-xl border bg-white p-6 space-y-5"><span className="badge">{profile.applicationStatus}</span><h2 className="display text-3xl">Show the work behind your work.</h2><p className="muted">Upload original evidence for the review team. Photography requires at least 10 portfolio photographs and 3 original RAW files. Verification evidence stays private.</p>{profile.reviewReason && <p className="error-box">{profile.reviewReason}</p>}<Upload purpose="verification" values={assets} onChange={setAssets} />{verification.map(a => <p className="muted text-sm" key={a._id}>{a.originalFilename} · {a.extension.toUpperCase()}</p>)}<button className="btn" disabled={busy} onClick={async () => { setBusy(true); setError(""); try { await api("/creator-workspace/verification", { method: "POST" }); await reload(); setSuccess("Verification submitted for review."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to submit."); } finally { setBusy(false); } }}>Submit verification</button>{["REJECTED", "SUSPENDED", "MORE_INFO_REQUIRED", "RESTRICTED"].includes(profile.applicationStatus) && <Link className="block underline text-brand" href="/creator/appeals">Submit an appeal</Link>}{error && <p role="alert" className="error-box">{error}</p>}{success && <p role="status">{success}</p>}</div>;
  return <form className="rounded-xl border bg-white p-6 space-y-5" onSubmit={async e => { e.preventDefault(); setBusy(true); setError(""); setSuccess(""); try { await api(calendar ? "/creator-workspace/availability" : "/creator-workspace/profile", { method: "PUT", body: JSON.stringify(calendar ? { availability: c.availability, timeSlots: c.timeSlots, weeklyHours: c.weeklyHours, temporaryLocations: c.temporaryLocations } : c) }); if (section === "locations") await api("/creator-workspace/availability", { method: "PUT", body: JSON.stringify({ availability: c.availability, timeSlots: c.timeSlots, temporaryLocations: c.temporaryLocations }) }); setSuccess("Your changes are saved."); } catch (e) { setError(e instanceof Error ? e.message : "Unable to save."); } finally { setBusy(false); } }}>
    {["settings", "services"].includes(section) && <>{([['businessName', 'Business name'], ['description', 'About your work'], ['city', 'Base city'], ['state', 'State']] as const).map(([key, label]) => <label className="field" key={key}>{label}<textarea value={c[key]} required minLength={key === "description" ? 20 : 1} onChange={e => setC(p => ({ ...p, [key]: e.target.value }))} /></label>)}<label className="field">Business type<select value={c.businessType} onChange={e => setC(p => ({ ...p, businessType: e.target.value }))}>{["INDIVIDUAL", "STUDIO", "AGENCY", "RENTAL_PROVIDER", "VENUE_PROVIDER"].map(s => <option key={s}>{s}</option>)}</select></label><label className="field">Experience (years)<input type="number" min={0} max={80} value={c.experience} onChange={e => setC(p => ({ ...p, experience: Number(e.target.value) }))} /></label>{([['languages', 'Languages'], ['services', 'Services offered'], ['eventTypes', 'Event types']] as const).map(([key, label]) => <label className="field" key={key}>{label} (one per line)<textarea value={c[key].join("\n")} onChange={e => setC(p => ({ ...p, [key]: e.target.value.split("\n") }))} /></label>)}</>}
    {section === "packages" && <>{c.packages.map((p, i) => <div className="rounded-lg border p-4 space-y-3" key={i}><label className="field">Package name<input required value={p.name} onChange={e => setC(c => ({ ...c, packages: c.packages.map((x, j) => j === i ? { ...x, name: e.target.value } : x) }))} /></label><label className="field">Price (INR)<input type="number" min={0} required value={p.price} onChange={e => setC(c => ({ ...c, packages: c.packages.map((x, j) => j === i ? { ...x, price: Number(e.target.value) } : x) }))} /></label><label className="field">Inclusions and delivery time<textarea required value={p.description} onChange={e => setC(c => ({ ...c, packages: c.packages.map((x, j) => j === i ? { ...x, description: e.target.value } : x) }))} /></label><button type="button" className="text-red-700 underline text-sm" onClick={() => setC(c => ({ ...c, packages: c.packages.filter((_, j) => j !== i) }))}>Remove package</button></div>)}<button type="button" className="btn btn-outline" onClick={() => setC(c => ({ ...c, packages: [...c.packages, { name: "", price: 0, description: "" }] }))}>Add package</button></>}
    {section === "portfolio" && <><p className="muted">Upload edited work for your public portfolio. Original verification files belong in Verification.</p><Upload purpose="portfolio" values={c.gallery} onChange={gallery => setC(c => ({ ...c, gallery }))} /><div className="grid grid-cols-2 sm:grid-cols-3 gap-3">{c.gallery.map((url, i) => <div key={`${url}-${i}`}><img src={url} alt={`Portfolio ${i + 1}`} className="h-32 w-full rounded object-cover" /><div className="flex gap-3 mt-2 text-xs"><button type="button" className="underline" onClick={() => setC(c => ({ ...c, profileImage: url }))}>Use as profile</button><button type="button" className="underline" onClick={() => setC(c => ({ ...c, coverImage: url }))}>Use as cover</button></div></div>)}</div></>}
    {calendar && <><h3 className="font-semibold">Recurring weekly hours</h3>{c.weeklyHours.map((slot,i) => <div className="grid gap-3 sm:grid-cols-4 border rounded p-3" key={i}><label className="field">Weekday<select value={slot.weekday} onChange={e => setC(c => ({...c, weeklyHours: c.weeklyHours.map((s,j) => j===i ? {...s, weekday:Number(e.target.value)} : s)}))}>{["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"].map((d,index) => <option key={d} value={index}>{d}</option>)}</select></label>{(["startTime","endTime"] as const).map(k => <label className="field" key={k}>{k}<input type="time" required value={slot[k]} onChange={e => setC(c => ({...c, weeklyHours: c.weeklyHours.map((s,j) => j===i ? {...s,[k]:e.target.value} : s)}))} /></label>)}<button type="button" className="text-xs underline" onClick={() => setC(c => ({...c,weeklyHours:c.weeklyHours.filter((_,j)=>j!==i)}))}>Remove</button></div>)}<button type="button" className="btn btn-outline" onClick={() => setC(c=>({...c,weeklyHours:[...c.weeklyHours,{weekday:1,startTime:"09:00",endTime:"18:00"}]}))}>Add recurring hours</button><p className="muted">Set available dates and optional hour ranges. Confirmed bookings reserve their hours and cannot overlap.</p><label className="field">Available dates (one YYYY-MM-DD per line)<textarea value={c.availability.join("\n")} onChange={e => setC(c => ({ ...c, availability: e.target.value.split("\n").filter(Boolean) }))} /></label>{c.timeSlots.map((s, i) => <div className="grid gap-3 sm:grid-cols-4 rounded border p-3" key={i}>{(["date", "startTime", "endTime"] as const).map(key => <label className="field" key={key}>{key}<input required type={key === "date" ? "date" : "time"} value={s[key]} onChange={e => setC(c => ({ ...c, timeSlots: c.timeSlots.map((x, j) => j === i ? { ...x, [key]: e.target.value } : x) }))} /></label>)}<label className="text-sm"><input type="checkbox" checked={s.blocked} onChange={e => setC(c => ({ ...c, timeSlots: c.timeSlots.map((x, j) => j === i ? { ...x, blocked: e.target.checked } : x) }))} /> Blocked</label><button type="button" className="text-xs underline" onClick={() => setC(c => ({ ...c, timeSlots: c.timeSlots.filter((_, j) => j !== i) }))}>Remove</button></div>)}<button className="btn btn-outline" type="button" onClick={() => setC(c => ({ ...c, timeSlots: [...c.timeSlots, { date: "", startTime: "09:00", endTime: "18:00", blocked: false }] }))}>Add hours / blocked period</button></>}
    {section === "locations" && <><label className="field">Service cities (one per line)<textarea value={c.serviceAreas.join("\n")} onChange={e => setC(c => ({ ...c, serviceAreas: e.target.value.split("\n") }))} /></label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={c.travelAvailable} onChange={e => setC(c => ({ ...c, travelAvailable: e.target.checked }))} />Available to travel</label><h3 className="font-semibold">Temporary work locations</h3>{c.temporaryLocations.map((s, i) => <div className="grid gap-3 sm:grid-cols-3" key={i}>{(["city", "from", "until"] as const).map(key => <label className="field" key={key}>{key}<input required type={key === "city" ? "text" : "date"} value={s[key]} onChange={e => setC(c => ({ ...c, temporaryLocations: c.temporaryLocations.map((x, j) => j === i ? { ...x, [key]: e.target.value } : x) }))} /></label>)}<button className="text-xs underline" type="button" onClick={() => setC(c => ({ ...c, temporaryLocations: c.temporaryLocations.filter((_, j) => j !== i) }))}>Remove location</button></div>)}<button type="button" className="btn btn-outline" onClick={() => setC(c => ({ ...c, temporaryLocations: [...c.temporaryLocations, { city: "", from: "", until: "" }] }))}>Add temporary location</button></>}
    {error && <p role="alert" className="error-box">{error}</p>}{success && <p role="status" className="text-emerald-700">{success}</p>}<button className="btn" disabled={busy}>{busy ? "Saving…" : "Save changes"}</button>
  </form>;
}
