"use client";
import { useState } from "react";
import { api } from "@/services/api";
export type Value = string | number | boolean | string[];
export type Field = { id: string; label: string; type: string; visibility?: string; optional?: boolean; disabled?: boolean; options?: string[]; help?: string; placeholder?: string; min?: number; max?: number; minLength?: number; maxLength?: number; maxFiles?: number; when?: { id: string; value: Value; operator?: string } };
export function visible(field: Field, answers: Record<string, Value>) {
  if (field.disabled) return false; if (!field.when) return true;
  const { id, value, operator } = field.when;
  if (operator === "notEquals") return answers[id] !== value;
  if (operator === "contains") return String(answers[id] || "").includes(String(value));
  if (operator === "in") return String(value).split(",").includes(String(answers[id]));
  return answers[id] === value;
}
export default function Fields({ fields, values, onChange }: { fields: Field[]; values: Record<string, Value>; onChange: (id: string, value: Value) => void }) {
  return <div className="grid gap-5">{fields.filter(f => visible(f, values)).map(f => <label className="field" key={f.id}>{f.label}{f.optional && <span className="muted text-xs">Optional</span>}
    {f.type === "section" || f.type === "information" ? <p className="muted">{f.help}</p> : ["file", "files", "image", "images", "video", "raw"].includes(f.type) ? <Upload purpose={f.type === "raw" || f.visibility === "ADMIN" ? "verification" : "reference"} values={Array.isArray(values[f.id]) ? values[f.id] as string[] : values[f.id] ? [String(values[f.id])] : []} onChange={v => onChange(f.id, ["files", "images"].includes(f.type) ? v : v[0] || "")} /> : ["date_range", "time_range"].includes(f.type) ? <div className="flex gap-3">{[0, 1].map(i => <input key={i} aria-label={`${f.label} ${i ? "end" : "start"}`} type={f.type === "date_range" ? "date" : "time"} required={!f.optional} value={(values[f.id] as string[] || [])[i] || ""} onChange={e => { const v = [...(values[f.id] as string[] || ["", ""])]; v[i] = e.target.value; onChange(f.id, v); }} />)}</div> : ["checkbox", "boolean"].includes(f.type) ? <input type="checkbox" required={!f.optional && f.type === "checkbox"} checked={values[f.id] === true} onChange={e => onChange(f.id, e.target.checked)} /> : f.type === "multiselect" ? <select multiple required={!f.optional} value={values[f.id] as string[] || []} onChange={e => onChange(f.id, Array.from(e.target.selectedOptions).map(o => o.value))}>{f.options?.map(o => <option key={o}>{o}</option>)}</select> : ["select", "radio"].includes(f.type) ? <select required={!f.optional} value={String(values[f.id] ?? "")} onChange={e => onChange(f.id, e.target.value)}><option value="">Choose</option>{f.options?.map(o => <option key={o}>{o}</option>)}</select> : ["textarea", "address"].includes(f.type) ? <textarea required={!f.optional} minLength={f.minLength} maxLength={f.maxLength || 5000} placeholder={f.placeholder} value={String(values[f.id] ?? "")} onChange={e => onChange(f.id, e.target.value)} /> : <input type={["price", "number"].includes(f.type) ? "number" : ["location", "currency"].includes(f.type) ? "text" : f.type} required={!f.optional} min={f.min} max={f.max} minLength={f.minLength} maxLength={f.maxLength || 5000} step={f.type === "price" ? "0.01" : undefined} value={String(values[f.id] ?? "")} placeholder={f.placeholder} onChange={e => onChange(f.id, ["number", "price"].includes(f.type) && e.target.value ? Number(e.target.value) : e.target.value)} />}
    {f.help && !["section", "information"].includes(f.type) && <span className="muted text-xs">{f.help}</span>}
  </label>)}</div>;
}
export function Upload({ purpose, contextId = "", values, onChange }: { purpose: string; contextId?: string; values: string[]; onChange: (values: string[]) => void }) {
  const [busy, setBusy] = useState(false), [error, setError] = useState("");
  return <div className="space-y-2"><input type="file" aria-label={`Upload ${purpose} file`} disabled={busy} accept={purpose === "verification" ? ".jpg,.jpeg,.png,.webp,.pdf,.mp4,.mov,.mxf,.cr2,.cr3,.nef,.arw,.raf,.orf,.rw2,.dng" : ".jpg,.jpeg,.png,.webp,.pdf,.mp4,.mov,.mxf"} onChange={async e => { const file = e.target.files?.[0]; if (!file) return; setBusy(true); setError(""); try { const body = new FormData(); body.append("file", file); body.append("purpose", purpose); body.append("contextId", contextId); const result = await api<{ _id: string; url?: string }>("/assets", { method: "POST", body, signal: AbortSignal.timeout(150000) }); onChange([...values, purpose === "portfolio" ? result.url! : result._id]); } catch (err) { setError(err instanceof Error ? err.message : "Upload failed."); } finally { setBusy(false); } }} /><p className="muted text-xs">{busy ? "Uploading…" : `${values.length} file(s) attached. Files are stored securely through Memooria.`}</p>{values.map((v, i) => <button className="mr-3 text-xs underline" type="button" key={v} onClick={() => onChange(values.filter(x => x !== v))}>Remove file {i + 1}</button>)}{error && <p className="error-box" role="alert">{error}</p>}</div>;
}
export function FileLink({ id, label = "Open file" }: { id: string; label?: string }) { const [url, setUrl] = useState(""), [error, setError] = useState(""); return <span>{url ? <a className="text-brand underline" href={url} target="_blank" rel="noopener noreferrer">{label} (5-minute link)</a> : <button type="button" className="text-brand underline" onClick={async () => { try { setUrl((await api<{ url: string }>(`/assets/${id}/access`)).url); } catch (e) { setError(e instanceof Error ? e.message : "Cannot open file."); } }}>{label}</button>}{error && <span role="alert" className="text-red-600">{error}</span>}</span>; }
