"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useResource } from "@/hooks/useResource";
import { api, money } from "@/services/api";
import CreatorCard from "@/components/CreatorCard";
import Loader from "@/components/Loader";
import type { Creator } from "@/services/types";
import BookingDetail from "./BookingDetail";
import RequirementDetail from "./RequirementDetail";
import CreatorSettings from "./CreatorSettings";
import Messages from "./Messages";
import { Upload, FileLink } from "./Fields";
export type Row = { _id: string; title?: string; name?: string; event?: string; city?: string; date?: string; status?: string; paymentStatus?: string; amount?: number; price?: number; message?: string; description?: string; reason?: string; explanation?: string; decision?: string; resolution?: string; services?: string[]; service?: string; requirement?: string; booking?: string; files?: string[]; link?: string; read?: boolean; matchingReason?: string };
export function State({ loading, error, reload }: { loading: boolean; error: string; reload: () => void }) { return loading ? <Loader label="Loading your workspace…" /> : error ? <div role="alert" className="error-box">{error}<button onClick={reload} className="ml-4 underline">Retry</button><Link className="ml-4 underline" href="/login">Sign in</Link></div> : null; }
const creatorSections = ["dashboard", "analytics", "drafts", "opportunities", "proposals", "bookings", "calendar", "services", "packages", "portfolio", "locations", "messages", "deliveries", "reviews", "verification", "appeals", "payments", "support", "settings"];
const customerSections = ["dashboard", "drafts", "bookings", "requirements", "proposals", "messages", "saved", "deliveries", "payments", "disputes", "profile", "support"];
export default function Workspace({ role, section, id }: { role: "customer" | "creator"; section: string; id?: string }) {
  return <div className="wrap section grid items-start gap-8 lg:grid-cols-[200px_1fr]"><aside className="rounded-xl border border-stone-200 bg-white p-5"><p className="eyebrow">YOUR {role.toUpperCase()} SPACE</p><nav className="flex gap-2 overflow-x-auto lg:flex-col">{(role === "creator" ? creatorSections : customerSections).map(s => <Link className={`whitespace-nowrap rounded px-3 py-2 text-sm capitalize ${section === s ? "bg-purple-50 text-brand font-semibold" : "muted"}`} href={`/${role}/${s}`} key={s}>{s}</Link>)}</nav><Link className="mt-5 block text-xs underline text-brand" href={role === "creator" ? "/customer/dashboard" : "/creator/dashboard"}>Switch workspace</Link></aside><main className="min-w-0"><p className="eyebrow">MEMOORIA WORKSPACE</p><h1 className="display text-4xl capitalize">{section === "dashboard" ? "Your next chapter." : section}</h1>
    {id && ["bookings", "projects"].includes(section) ? <BookingDetail id={id} role={role} /> : id && ["requirements", "opportunities"].includes(section) ? <RequirementDetail id={id} role={role} /> : section === "messages" ? <Messages /> : role === "creator" && ["calendar", "services", "packages", "portfolio", "locations", "verification", "settings"].includes(section) ? <CreatorSettings section={section} /> : ["dashboard", "analytics"].includes(section) ? <Overview role={role} /> : section === "drafts" ? <Drafts role={role} /> : section === "saved" ? <Saved /> : ["appeals", "disputes"].includes(section) ? <Cases kind={section as "appeals" | "disputes"} /> : section === "payments" ? <Payments /> : section === "profile" ? <Profile /> : section === "support" ? <Support /> : section === "reviews" ? <p className="muted">Reviews from completed bookings appear on your public creator profile. Reviews are moderated by Memooria.</p> : <Collection section={section} role={role} />}
  </main></div>;
}
function Overview({ role }: { role: string }) {
  const resource = useResource<Record<string, number>>("/workspace?role="+role); const notices = useResource<Row[]>("/notifications");
  return <><State {...resource} /><div className="grid grid-cols-2 gap-4 xl:grid-cols-4">{Object.entries(resource.data || {}).map(([key, value]) => <div className="rounded-xl border bg-white p-5" key={key}><p className="muted text-xs capitalize">{key}</p><p className="text-3xl font-semibold">{value}</p></div>)}</div><div className="my-6 flex flex-wrap gap-3"><Link className="btn" href={role === "creator" ? "/creator/opportunities" : "/post-requirement"}>{role === "creator" ? "Find opportunities" : "Post a requirement"}</Link><Link className="btn btn-outline" href="/explore">Explore creators</Link></div><h2 className="display text-2xl">Updates for you</h2><State {...notices} />{notices.data?.map(n => <Link className={`block border-b py-4 text-sm ${n.read ? "muted" : "font-semibold"}`} href={n.link || `/${role}/dashboard`} key={n._id} onClick={() => { void api(`/notifications/${n._id}`, { method: "PATCH" }); }}>{n.title}</Link>)}{notices.data?.length === 0 && <p className="muted">Your booking and application updates will appear here.</p>}</>;
}
function Collection({ section, role }: { section: string; role: string }) {
  const path = section === "opportunities" ? "/requirements?mode=opportunities" : `/${section}`;
  const r = useResource<Row[]>(path);
  return <><State {...r} />{section === "requirements" && <Link className="btn mb-5" href="/post-requirement">Post a requirement</Link>}<div className="grid gap-4">{r.data?.map(row => { const link = section === "proposals" ? `/${role}/${role === "creator" ? "opportunities" : "requirements"}/${row.requirement}` : section === "deliveries" ? `/${role}/bookings/${row.booking}` : `/${role}/${section}/${row._id}`; return <article className="rounded-xl border border-stone-200 bg-white p-6" key={row._id}><div className="flex flex-wrap justify-between gap-3"><h2 className="display text-2xl">{row.title || row.event || "Proposal"}</h2><span className="badge">{row.status?.replaceAll("_", " ")}</span></div><p className="muted text-sm">{[row.city, row.date, row.service || row.services?.join(", ")].filter(Boolean).join(" · ")}</p>{(row.amount !== undefined || row.price !== undefined) && <p className="font-semibold">{money(row.amount ?? row.price ?? 0)}</p>}{row.matchingReason && <p className="muted text-xs">{row.matchingReason}</p>}<Link className="text-brand underline text-sm" href={link}>View details</Link></article>; })}</div>{r.data?.length === 0 && <div className="rounded-xl border border-dashed p-10 text-center muted">No {section} yet. Updates will appear here as your plans take shape.</div>}</>;
}
function Saved() { const r = useResource<Creator[]>("/saved"); return <><State {...r} /><div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{r.data?.map(c => <CreatorCard creator={c} key={c._id} />)}</div>{r.data?.length === 0 && <p className="muted">Save creators while exploring to build your shortlist.</p>}</>; }
function Payments() { const r = useResource<Row[]>("/bookings"); return <><p className="muted">Demo payment records are confirmed by Memooria administrators. No money is charged and no payouts are transferred.</p><State {...r} />{r.data?.map(b => <div className="border-b py-4 flex justify-between gap-4" key={b._id}><span>{b.title}</span><span>{money(b.amount || 0)} · {b.paymentStatus}</span></div>)}</>; }
function Cases({ kind }: { kind: "appeals" | "disputes" }) {
  const r = useResource<Row[]>(`/${kind}`); const [files, setFiles] = useState<string[]>([]), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  return <><p className="muted">{kind === "appeals" ? "Request another review of a rejected or suspended creator application." : "Tell Memooria about a problem with a confirmed booking."}</p><form className="rounded-xl border bg-white p-6 space-y-4 mb-8" onSubmit={async e => { e.preventDefault(); const form = e.currentTarget; setError(""); setBusy(true); try { await api(`/${kind}`, { method: "POST", body: JSON.stringify({ ...Object.fromEntries(new FormData(form)), files }) }); form.reset(); setFiles([]); await r.reload(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to submit."); } finally { setBusy(false); } }}>
    {kind === "disputes" && <label className="field">Booking ID<input name="booking" required /></label>}<label className="field">Reason<textarea name="reason" required minLength={kind === "appeals" ? 3 : 20} maxLength={5000} /></label>{kind === "appeals" && <label className="field">Explain your appeal<textarea name="explanation" required minLength={20} maxLength={5000} /></label>}<Upload purpose={kind === "appeals" ? "appeal" : "reference"} values={files} onChange={setFiles} />{error && <p role="alert" className="error-box">{error}</p>}<button className="btn" disabled={busy}>{busy ? "Submitting…" : "Submit for review"}</button></form><State {...r} />{r.data?.map(x => <article className="border-b py-5" key={x._id}><span className="badge">{x.status}</span><p>{x.reason}</p><p className="muted">{x.decision || x.resolution || "Awaiting review"}</p>{x.files?.map(id => <FileLink key={id} id={id} />)}</article>)}</>;
}
function Profile() {
  const r = useResource<{ name: string; email: string; phone?: string }>("/auth/me"), [message, setMessage] = useState("");
  return <><State {...r} />{r.data && <form className="rounded-xl border bg-white p-6 space-y-4" onSubmit={async e => { e.preventDefault(); try { await api("/users/me", { method: "PATCH", body: JSON.stringify(Object.fromEntries(new FormData(e.currentTarget))) }); setMessage("Profile saved."); await r.reload(); } catch (e) { setMessage(e instanceof Error ? e.message : "Unable to save."); } }}><label className="field">Your name<input name="name" required defaultValue={r.data.name} /></label><label className="field">Phone<input name="phone" type="tel" defaultValue={r.data.phone || ""} maxLength={30} /></label><p className="muted text-sm">{r.data.email}</p><button className="btn">Save profile</button><Link href="/register" className="block underline text-brand">Update your interests</Link>{message && <p role="status">{message}</p>}</form>}</>;
}
function Support() { const [error, setError] = useState(""); return <><p className="muted">Contact the Memooria team about your account, booking or delivery.</p><button className="btn" onClick={async () => { try { await api("/conversations", { method: "POST", body: JSON.stringify({ context: "SUPPORT" }) }); window.location.href = "/customer/messages"; } catch (e) { setError(e instanceof Error ? e.message : "Unable to start support chat."); } }}>Message support</button>{error && <p role="alert">{error}</p>}</>; }

function Drafts({role}:{role:string}) { const r=useResource<{key:string;kind:string;values:{title?:string;creator?:string;service?:string;requirement?:string};updatedAt:string}[]>("/drafts");return <><State {...r}/>{r.data?.map(d=><article className="rounded-xl border bg-white p-5 mb-3" key={d.key}><h2 className="display text-2xl">{d.values.title || d.kind+" draft"}</h2><p className="muted text-xs">Saved {new Date(d.updatedAt).toLocaleString()}</p><Link className="btn btn-outline" href={d.kind==="proposal" ? "/creator/opportunities/"+d.values.requirement : d.kind==="booking" ? "/request-booking?creator="+d.values.creator+"&service="+encodeURIComponent(d.values.service||"") : "/post-requirement"}>Resume draft</Link><button className="ml-4 text-xs underline" onClick={async()=>{if(confirm("Delete this saved draft?")){await api("/drafts/"+d.key,{method:"DELETE"});await r.reload();}}}>Delete draft</button></article>)}{r.data?.length===0&&<p className="muted">Your saved requests and proposals will appear here.</p>}</>;}
